name: pushToCode
options:
  bundleIdPrefix: com.pushtocode
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    ENABLE_USER_SCRIPT_SANDBOXING: false

targets:
  pushToCode:
    type: application
    platform: iOS
    deploymentTarget: "16.0"

    sources:
      - path: pushToCode/Sources
        type: group
      - path: pushToCode/Resources
        type: group
      - path: pushToCode/Info.plist
        type: file
        buildPhase: none

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pushtocode.app
        INFOPLIST_FILE: pushToCode/Info.plist
        GENERATE_INFOPLIST_FILE: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

    info:
      path: pushToCode/Info.plist
      properties:
        NSMicrophoneUsageDescription: "pushToCode needs microphone access to record voice commands for Claude."
        UIBackgroundModes:
          - audio

schemes:
  pushToCode:
    build:
      targets:
        pushToCode: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
